-- MySQL Script generated by MySQL Workbench
-- 01/11/17 22:56:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cheladocs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cheladocs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cheladocs` DEFAULT CHARACTER SET utf8 ;
USE `cheladocs` ;

-- -----------------------------------------------------
-- Table `cheladocs`.`requerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`requerente` (
  `id_requerente` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_juridica` VARCHAR(45) NULL DEFAULT NULL,
  `nome_requerente` VARCHAR(45) NULL,
  `sobrenome_requerente` VARCHAR(45) NULL DEFAULT NULL,
  `telefone_principal` VARCHAR(45) NULL DEFAULT NULL,
  `telefone_alternativo_requerente` VARCHAR(45) NULL DEFAULT NULL,
  `email_principal_requerente` VARCHAR(45) NULL,
  `email_alternativo_requerente` VARCHAR(45) NULL DEFAULT NULL,
  `home_page_requerente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_requerente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`departamento` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`natureza_assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`natureza_assunto` (
  `id_natureza_assunto` INT(11) NOT NULL AUTO_INCREMENT,
  `natureza_assunto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_natureza_assunto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`tipo_expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`tipo_expediente` (
  `id_tipo_expediente` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_expediente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_expediente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`documento` (
  `numero_protocolo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_requerente` INT(11) NOT NULL,
  `data_entrada` DATE NULL DEFAULT NULL,
  `origem` VARCHAR(45) NULL,
  `descricao_assunto` VARCHAR(45) NULL DEFAULT NULL,
  `id_natureza_assunto` INT(11) NOT NULL,
  `id_tipo_expediente` INT(11) NOT NULL,
  `url_ficheiro_documento` VARCHAR(100) NULL DEFAULT NULL,
  `conteudo_documento` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`numero_protocolo`),
  INDEX `fk_documento_natureza_assunto_idx` (`id_natureza_assunto` ASC),
  INDEX `fk_documento_tipo_expediente1_idx` (`id_tipo_expediente` ASC),
  INDEX `fk_documento_solicitante1_idx` (`id_requerente` ASC),
  CONSTRAINT `fk_documento_natureza_assunto`
    FOREIGN KEY (`id_natureza_assunto`)
    REFERENCES `cheladocs`.`natureza_assunto` (`id_natureza_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_tipo_expediente1`
    FOREIGN KEY (`id_tipo_expediente`)
    REFERENCES `cheladocs`.`tipo_expediente` (`id_tipo_expediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_solicitante1`
    FOREIGN KEY (`id_requerente`)
    REFERENCES `cheladocs`.`requerente` (`id_requerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`pais` (
  `id_pais` CHAR(20) NOT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`provincia` (
  `id_provincia` INT(11) NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `id_pais` CHAR(20) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  INDEX `fk_provincia_pais1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_provincia_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `cheladocs`.`pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`municipio` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL,
  `id_provincia` INT(11) NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_municipio_provincia1_idx` (`id_provincia` ASC),
  CONSTRAINT `fk_municipio_provincia1`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `cheladocs`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cheladocs`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`endereco` (
  `id_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `caixa_postal` VARCHAR(45) NULL DEFAULT NULL,
  `rua_endereco` VARCHAR(45) NULL DEFAULT NULL,
  `casa_endereco` VARCHAR(45) NULL DEFAULT NULL,
  `bairro_endereco` VARCHAR(45) NULL DEFAULT NULL,
  `cidade_endereco` VARCHAR(45) NULL DEFAULT NULL,
  `id_requerente` INT(11) NOT NULL,
  `flag_activo` BIT NOT NULL,
  `id_municipio` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_requerente1_idx` (`id_requerente` ASC),
  INDEX `fk_endereco_municipio1_idx` (`id_municipio` ASC),
  CONSTRAINT `fk_endereco_requerente1`
    FOREIGN KEY (`id_requerente`)
    REFERENCES `cheladocs`.`requerente` (`id_requerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `cheladocs`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cheladocs`.`movimento_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheladocs`.`movimento_documento` (
  `id_movimento_progressivo` INT(11) NOT NULL AUTO_INCREMENT,
  `data_recepcao` DATETIME NULL DEFAULT NULL,
  `data_reenvio` DATETIME NULL DEFAULT NULL,
  `id_departamento` INT(11) NOT NULL,
  `notas` VARCHAR(200) NULL DEFAULT NULL,
  `numero_protocolo` INT(11) NOT NULL,
  PRIMARY KEY (`id_movimento_progressivo`),
  INDEX `fk_movimento_documento_departamento1_idx` (`id_departamento` ASC),
  INDEX `fk_movimento_documento_documento1_idx` (`numero_protocolo` ASC),
  CONSTRAINT `fk_movimento_documento_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `cheladocs`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_documento_documento1`
    FOREIGN KEY (`numero_protocolo`)
    REFERENCES `cheladocs`.`documento` (`numero_protocolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
